export function AutoGenerated() {
  return (
    <div className='flex items-center'>
      <div className='rounded-lg bg-yellow-300 text-yellow-800'>
        <p className='pl-2 pr-2 pt-1 pb-1'>Auto-Generated</p>
      </div>
    </div>
  )
}