name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.0

      - name: Install Dependencies
        run: npm install

      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get_latest_tag

      - name: Set up App Version
        run: |
          npm version ${{ steps.get_latest_tag.outputs.tag }} --no-git-tag-version --allow-same-version
          npm version minor --no-git-tag-version --allow-same-version
        
      - name: Generate .env
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL_DEV }}" >> .env
          echo "VITE_GOOGLE_MAPS_JAVASCRIPT_API_KEY=${{ secrets.VITE_GOOGLE_MAPS_JAVASCRIPT_API_KEY_DEV }}" >> .env
          echo "VITE_GOOGLE_MAPS_MAP_ID=${{ secrets.VITE_GOOGLE_MAPS_MAP_ID_DEV }}" >> .env
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY_DEV }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN_DEV }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID_DEV }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET_DEV }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID_DEV }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID_DEV }}" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID_DEV }}" >> .env
          echo "VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY_DEV }}" >> .env

      - name: Build
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with: 
          name: dist
          path: dist

      - name: Notify Build End
        if: failure()
        uses: 8398a7/action-slack@v3
        with: 
          status: ${{ job.status }}
          fields: repo,author,ref,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Setup Firebase Tools
        uses: w9jds/setup-firebase@main
        with:
          tools-version: 13.29.1
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Select Configuration
        run: firebase use dev

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting

      - name: Notify Deployment End
        if: always()
        uses: 8398a7/action-slack@v3
        with: 
          status: ${{ job.status }}
          fields: repo,author,ref,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}