name: Deploy to Production

on:
  release:
    types: released

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.0

      - name: Install Dependencies
        run: npm install

      - name: Set up App Version
        run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version --allow-same-version
        
      - name: Generate .env
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env
          echo "VITE_GOOGLE_MAPS_JAVASCRIPT_API_KEY=${{ secrets.VITE_GOOGLE_MAPS_JAVASCRIPT_API_KEY }}" >> .env
          echo "VITE_GOOGLE_MAPS_MAP_ID=${{ secrets.VITE_GOOGLE_MAPS_MAP_ID }}" >> .env
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
          echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env
          echo "VITE_RECAPTCHA_SITE_KEY=${{ secrets.VITE_RECAPTCHA_SITE_KEY }}" >> .env

      - name: Build
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with: 
          name: dist
          path: dist

      - name: Notify Build End
        if: failure()
        uses: 8398a7/action-slack@v3
        with: 
          status: ${{ job.status }}
          fields: repo,author,ref,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Setup Firebase Tools
        uses: w9jds/setup-firebase@main
        with:
          tools-version: 13.29.1
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Select Configuration
        run: firebase use prod

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --message \"${{ github.event.release.tag_name }}\"
        
      - name: Notify Deployment End
        if: always()
        uses: 8398a7/action-slack@v3
        with: 
          status: ${{ job.status }}
          fields: repo,author,ref,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}